### ISSUE TITLE
Issue with Building Placement and AI

### ISSUE THREAD

**Issue by magxmaDUCK** [npruehs/ue4-rts#178] opened 2022-02-18 20:22 UTC
For the Building placement, I have a unit (made from a character) that can build a house. The unit moves to the build site but randomly starts building or not. It also seems that the unit has a jitter uppon arrival at the build site. I have also tried the same with a unit using the RTSMovementComponent and have the exact same result.

For the AI, Well it simply doesn't auto attack other units in range. They only attack if I explicitly tell them to, and  only attack the aimed unit. I have followed the Manual to make the units and the only difference is that i did not add the "RTSAttackableComponent" as it doesnt show up in the add component window, so I'm guessing it was changed with the gameplay tag. 

I also wanted to thank you for this great plugin !

**Comment by npruehs** [comment] 2022-02-18 22:13
Unfortunately, both of these sound like bugs I need to look into...

**Comment by magxmaDUCK** [comment] 2022-02-19 18:19
I had a look in the C++ and it seems like auto-attack isnt pre made, I found the functions needed to do it however when looking for references to them there aren't any that come back, so i'm guessing the units not auto attacking is not a bug but is simply just not implemented ?

However for the building part I have yet to figure it out, it really is a random occurence. If I find anything I will keep you updated !

**Comment by ForgottenFrog** [comment] 2022-02-26 01:14
Hi, I found the same problem. The AI perception is not implemented. In C++ it is mentioned, but never triggered.

**Comment by npruehs** [comment] 2022-02-27 22:11
I can confirm this has been multiple bugs, actually. While you've been right in that the function `FindTargetInAcquisitionRadius` isn't called anywhere in C++, it's called in the behavior tree service `RTSBTService_AcquireTargets`. However, I've found a bug in that service that caused the AI to check whether the unit's target was valid (which is never the case while the unit is idle). 

Then, I've found a second bug in how the AI was sweeping for nearby possible targets. I've added a configuration property _Acquisition Object Types_ to the `RTSPawnAIController` that you need to set in your pawn AI controller blueprint (e.g. to `WorldDynamic` or `Pawn`, depending on the collision object types you're using for your units). I've updated the manual accordingly. 

Fixed in https://github.com/npruehs/ue4-rts/commit/384c55198cd0a7cd3a444164c3e6936c02275783.

**Closed as completed by npruehs** 2022-02-27 22:11 UTC
Labels: bug

**Comment by ForgottenFrog** [comment] 2022-03-02 01:54
Hi @npruehs ,

Sorry to bother you again, but after making this change, the project just doesn't want compile again...I've even downloaded the source version of the engine, but still...no result...
The project always fails in compiling back. It still works, but the sense AI never gets built.
I've tried to download the new version of the project, but it also fails to build...(weirdly, only with the ue4 project open), when it is closed, it builds up, but still, with no result...
Could you, please, if possible, maybe...create a new branch or upload on cloud a version of the project with working AI and that can be compiled?😅
I'm more than sure that the problem is on my side, but please, can you help me with this one thing?🥺
